export const extractTimesFromWorkflow = (workflowYaml) => {
  const times = [];
  try {
    const cronRegex = /- cron:\s*['"](.*?)['"]/g;
    let match;
    while ((match = cronRegex.exec(workflowYaml)) !== null) {
      const cronStr = match[1]; // e.g. "30 5,13,21 * * *"
      const parts = cronStr.trim().split(/\s+/);
      if (parts.length >= 2) {
        const minute = parts[0];
        const hours = parts[1].split(','); // in UTC
        
        for (let h of hours) {
          const utcHour = parseInt(h.trim(), 10);
          if (!isNaN(utcHour)) {
            // Convert UTC to UTC+8
            const localHour = (utcHour + 8) % 24;
            const timeStr = `${localHour.toString().padStart(2, '0')}:${minute.padStart(2, '0')}`;
            times.push(timeStr);
          }
        }
      }
    }
  } catch (e) {
    console.error("Error parsing cron:", e);
  }
  // Sort times for nice display
  return times.sort();
};

export const updateWorkflowTimes = (workflowYaml, newTimesList) => {
  // newTimesList is array of "HH:MM" (local UTC+8 times)
  
  // Generate the new schedule block strings
  const cronLines = newTimesList.map(t => {
    const [hh, mm] = t.split(':');
    const localHour = parseInt(hh, 10);
    const minute = parseInt(mm, 10);
    const utcHour = (localHour + 24 - 8) % 24;
    return `    - cron: '${minute} ${utcHour} * * *'`;
  });
  
  const scheduleBlock = `  schedule:\n    # Auto-generated by UI (Local Time UTC+8)\n${cronLines.join('\n')}\n`;
  
  // Replace the old schedule block
  // Using regex to find the block between 'schedule:' and 'workflow_dispatch:'
  const replaceRegex = /(schedule:\s*\n[\s\S]*?)(\s*#\s*Allow manual trigger|\s*workflow_dispatch:)/;
  
  if (replaceRegex.test(workflowYaml)) {
    return workflowYaml.replace(replaceRegex, `${scheduleBlock}$2`);
  }
  
  // If fallback:
  return workflowYaml;
};
